<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
	<head>
		<?php echo $this->getChildHtml('head') ?>
		<base target="_parent" />
	</head>
	<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
		<div class="container">
			<div id="quicklook-main" class="quicklook-main">
				<?php echo $this->getChildHtml('content') ?>
				<input type="hidden" class="viewquickloook" name="quicklook" value="1" />
			</div> 
		</div> 
	</body>
</html>