<?php 
/*------------------------------------------------------------------------
# APL Solutions and Vision Co., LTD
# ------------------------------------------------------------------------
# Copyright (C) 2008-2010 APL Solutions and Vision Co., LTD. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: APL Solutions and Vision Co., LTD
# Websites: http://www.joomlavision.com/ - http://www.magentheme.com/
-------------------------------------------------------------------------*/ 
?>
<?php 
    $_direct = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/direction');
    $_items = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/items');
    $_thumb_w = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/width');
    $_thumb_h = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/height');
    $_show_control = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/control');
    $_auto_scroll = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/auto_scroll');
    $_speed = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/speed');
    $_top_vert = $_items*$_thumb_h + $_items*8 + 24;
    $_left_hor = $_items*$_thumb_w + $_items*9 + 14;
    $_count_thumb = 0;
    $_left_ctr = ($_thumb_w/2) - 20; 
    $_top_ctr = ($_thumb_h-20)/2;
    $_zoom_w = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/width_z');
    $_zoom_h = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/height_z');
    $_lightbox_w = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/width_lbox');    
    $_lightbox_h = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/height_lbox');
    $_enabled_zoom = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/enabled_zoom');
    $_enabled_scroller = Mage::getStoreConfig('mtlaniusadmin/thumbnailscroller/enabled_scroller'); 
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php if( $_direct == "vertical") { // is vertical scroller thumbnail ?>
    <?php if (count($this->getGalleryImages()) > 0): ?>
        <div class="mt-more-images mt-vert-thumb">
            <div class="more-views">
                <div class="mt-more-views">
                    <ul>
                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                        <?php $_count_thumb ++;?>
                        <li>
                            <?php if($_enabled_zoom) {?>
                                <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(1200,1200); ?>" class="cloud-zoom-gallery" title="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>"
                                rel="useZoom: 'mt-zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(400,400); ?>'">
                               		<img class="imgbox" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_thumb_w-4,$_thumb_h-4); ?>" width="<?php echo $_thumb_w-4; ?>" height = "<?php echo $_thumb_h-4; ?>" alt = ""/>
                               </a> 
                            <?php } else { ?>
                                <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                                	<img class="imgbox" src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumb_w-4,$_thumb_h-4); ?>" width="<?php echo $_thumb_w-4;?>" height="<?php echo $_thumb_h-4; ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                                </a>                       
                            <?php } ?>
                        </li>
                    <?php endforeach; ?>                                                                
                    </ul> 
                </div>
                <!-- thumbnail for lighbox-->
                <?php if($_enabled_zoom) {?>
                    <ul class="mt-thumb-light" style="display:none;">
                        <?php foreach ($this->getGalleryImages() as $_image): ?>
                            <li>
                                <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>" rel="lightbox[rotation]" title="<?php echo $_product->getName();?>"></a>
                            </li>
                        <?php endforeach; ?>                                                                
                    </ul>
                <?php } ?>
                <!--##########-->
            </div>
            <?php if (( $_count_thumb > $_items )&& ($_show_control) && ($_enabled_scroller)) { // if thumbnail > items show ?>
                <span class="prev">&nbsp;</span>
                <span class="next">&nbsp;</span>
            <?php } ?>            
        </div>
    <?php endif; ?>    
    <script type="text/javascript">
        $mtkb(document).ready(function(){
            $mtkb(".product-view .product-img-box").css("width","340px");
            $mtkb(".product-view .product-shop").css("width","275px");
            $mtkb(".mt-more-images").css("width","<?php echo $_thumb_w; ?>px");
            $mtkb(".mt-more-images").css("float","left");
            $mtkb(".product-view .product-img-box .product-image-zoom").css("float","right");
            $mtkb(".product-view .product-img-box .zoom-notice").css("float","right");
            $mtkb(".product-view .product-img-box .zoom").css("float","right");
            $mtkb(".product-view .product-img-box .zoom").css("width","200px");
            $mtkb(".product-view .product-img-box .zoom").css("padding","0 22px");            
            $mtkb(".product-view .product-img-box .zoom-notice").css("width","260px");
            $mtkb(".product-view .product-img-box .zoom-notice").css("float","right");
            $mtkb(".product-view .product-img-box .more-views li").css("width","<?php echo $_thumb_w;?>px");
            $mtkb(".product-view .product-img-box .more-views li").css("height","<?php echo $_thumb_h;?>px");
            $mtkb(".product-view .product-img-box .more-views li").css("margin","0 0 8px 0");
            $mtkb(".product-view .product-img-box .more-views li a").css("width","<?php echo $_thumb_w-4;?>px");
            $mtkb(".product-view .product-img-box .more-views li a").css("height","<?php echo $_thumb_h-4;?>px");
            <?php if(( $_count_thumb > $_items ) && ($_show_control) && ($_enabled_scroller)) { // if thumbnail > items show ?>
                $mtkb(".mt-more-views").css("margin-top","20px");
                $mtkb(".product-view .mt-vert-thumb .next").css("top","<?php echo $_top_vert;?>px");
                $mtkb(".product-view .mt-vert-thumb .next, .product-view .mt-vert-thumb .prev").css("left","<?php echo $_left_ctr; ?>px");
            <?php } ?>
            <?php if($_enabled_zoom) {?>
                $mtkb(".mt-more-views li a").click(function(){
                    $mtkb("a.mt-a-lighbox").attr("href",$mtkb(this).attr("title"));
                });
            <?php } ?>
        });
        <?php if (( $_count_thumb > $_items ) && ($_enabled_scroller)) { // if thumbnail > items show ?>
            $mtkb(function() {
               $mtkb(".mt-more-views").jCarouselLite({
                    <?php if ($_show_control) { ?>
                        btnPrev: ".prev",
                        btnNext: ".next",
                    <?php } ?>
                    vertical: true,
                    hoverPause:true,
                    visible: <?php echo $_items;?>,
                    auto:<?php echo $_auto_scroll;?>,
                    speed:<?php echo $_speed; ?>
               });
            });
        <?php } ?>
    </script>    
<?php } // end vertical scroller thumbnail ?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <?php
                $_img = '<img id="image" src="'.$this->helper('catalog/image')->init($_product, 'image').'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                //echo $_helper->productAttribute($_product, $_img, 'image');                
            ?>
            <?php if($_enabled_zoom) {?>
                <!-- images for lightbox -->
                <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_lightbox_w, $_lightbox_h); ?>" class = "mt-a-lighbox" rel="lightbox[rotation]"></a>
                <!--++++++++++++-->
                <a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(900,900); ?>" class = "cloud-zoom" id="mt-zoom1" style="position: relative; display: block;" rel="adjustX:10, adjustY:-2, zoomWidth:<?php echo $_zoom_w; ?>, zoomHeight:<?php echo $_zoom_h;?>">
                    <img class="imgbox"  src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(300,300); ?>" alt='' title="Optional title display" />
                </a>
                <script type="text/javascript">
                    $mtkb(".product-view .product-img-box .product-image-zoom").css("overflow","visible");
                </script>
            <?php } else {
                echo $_helper->productAttribute($_product, $_img, 'image');   
            }?>
        </p>
        <?php if($_enabled_zoom == 0){ ?>
        <p class="zoom-notice" id="track_hint"><?php echo $this->__('Double click on above image to view full picture') ?></p>
        <div class="zoom">
            <img id="zoom_out" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'magenthemes/mtthumbnailscroller/images/slider_btn_zoom_out.gif';?>" alt="<?php echo $this->__('Zoom Out') ?>" title="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out" />
            <div id="track">
                <div id="handle"></div>
            </div>
            <img id="zoom_in" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB).'magenthemes/mtthumbnailscroller/images/slider_btn_zoom_in.gif'; ?>" alt="<?php echo $this->__('Zoom In') ?>" title="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in" />
        </div>
        <script type="text/javascript">
        //<![CDATA[

            Event.observe(window, 'load', function() {
                product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out', 'track_hint');
            });
        //]]>
        </script>
        <?php } ?>
        <?php else: ?>
        <p class="product-image">
            <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(400).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
<?php endif; ?>

<?php if( $_direct == "horizontal") { // is horizontal scroller thumbnail ?>
    <?php if (count($this->getGalleryImages()) > 0): ?>
        <div class="mt-more-images">
            <div class="more-views">
                <h2 style="display: none;"><?php echo $this->__('More Views') ?></h2>
                <div class="mt-more-views">
                    <ul>
                    <?php foreach ($this->getGalleryImages() as $_image): ?>
                        <?php $_count_thumb ++;?>
                        <li>
                            <?php if($_enabled_zoom) {?>
                                <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(1200,1200); ?>" class="cloud-zoom-gallery" title="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>"
                                rel="useZoom: 'mt-zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(400,400); ?>'">
                               <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_thumb_w-4,$_thumb_h-4); ?>" width="<?php echo $_thumb_w-4; ?>" height = "<?php echo $_thumb_h-4; ?>" alt = ""/></a> 
                            <?php } else { ?>
                                <a href="#" onclick="popWin('<?php echo $this->getGalleryUrl($_image) ?>', 'gallery', 'width=300,height=300,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes'); return false;" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumb_w-4,$_thumb_h-4); ?>" width="<?php echo $_thumb_w-4;?>" height="<?php echo $_thumb_h-4; ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>                       
                            <?php } ?>
                        </li>
                    <?php endforeach; ?>                                                                
                    </ul>       
                </div>
                <!-- thumbnail for lighbox-->
                <?php if($_enabled_zoom) {?>
                    <ul class="mt-thumb-light" style="display:none;">
                        <?php foreach ($this->getGalleryImages() as $_image): ?>
                            <li>
                                <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>" rel="lightbox[rotation]" title="<?php echo $_product->getName();?>"></a>
                            </li>
                        <?php endforeach; ?>                                                                
                    </ul>
                <?php } ?>
                <!--##########-->
            </div>
            <?php // if thumbnail > items show  ?>
            <?php if (($_count_thumb > $_items) && ($_show_control) && ($_enabled_scroller)) {?>
                <span class="prev">&nbsp;</span>
                <span class="next">&nbsp;</span>
            <?php } ?>            
        </div>
        
        <script type="text/javascript">
            <?php if (( $_count_thumb > $_items) && ($_enabled_scroller)) {?>
                $mtkb(function() {
                   $mtkb(".mt-more-views").jCarouselLite({
                        <?php if($_show_control) { ?>
                            btnPrev: ".prev",
                            btnNext: ".next",
                        <?php } ?>
                        vertical: false,
                        hoverPause:true,
                        visible: <?php echo $_items;?>,
                        auto: <?php echo $_auto_scroll; ?>,
                        speed: <?php echo $_speed; ?>
                   });
                });                
                $mtkb(".product-view .product-img-box .more-views mt-more-views li").css("width","<?php echo $_thumb_w;?>px");
                $mtkb(".product-view .product-img-box .more-views mt-more-views li").css("height","<?php echo $_thumb_h;?>px");
                $mtkb(".product-view .product-img-box .more-views mt-more-views li a").css("width","<?php echo $_thumb_w-4;?>px");
                $mtkb(".product-view .product-img-box .more-views mt-more-views li a").css("height","<?php echo $_thumb_h-4;?>px");
                <?php if($_show_control) { ?>
                    $mtkb(".product-view .next, .product-view .prev").css("top","<?php echo $_top_ctr;?>px");
                <?php } ?>                
            <?php } ?>
            <?php if($_enabled_zoom) {?>
                //<![CDATA[
                $mtkb("head").append('<style type="text/css">#imageContainer #lightboxImage { width:<?php echo $_lightbox_w; ?>px; height:<?php echo $_lightbox_h;?>px;}</style>');
                //]]>
            <?php } ?>
            $mtkb(document).ready(function(){
                    <?php if($_enabled_zoom) {?>
                        $mtkb(".mt-more-views li a").click(function(){
                            $mtkb("a.mt-a-lighbox").attr("href",$mtkb(this).attr("title"));
                        });
                    <?php } ?>
                });
        </script>
        
    <?php endif; ?>    
<?php } // end horizontal scroller thumbnail ?>